#ifndef CHESS_H_INCLUDED
#define CHESS_H_INCLUDED

#define SQUARE_RANGE         1
#define DOUBLE_SQUARE_RANGE  2
#define L_RANGE              4
#define LINE_OF_SIGHT        8
#define RANGE_TYPE_NONE      0

#define SHORT_CASTLE_TYPE  0x01
#define LONG_CASTLE_TYPE   0x02
#define BOTH_CASTLE_TYPE   SHORT_CASTLE_TYPE | LONG_CASTLE_TYPE

#define GET_BOOLEAN_POSSIBILITY  false
#define GET_POSSIBLE_TYPES  true

#define CONSIDER_COLISION  false
#define IGNORE_COLISION  true
#define MOVEMENT_TYPE_NONE  0
//
// Main movement notation
//
#define MOVEMENT_DIRECTION_COLUMN    0x01
#define MOVEMENT_DIRECTION_LINE      0x02
#define MOVEMENT_DIRECTION_DIAGONAL  0x04
#define MOVEMENT_DIRECTION_L         0x08
//
// Segemented movement notation
//
#define SUBTYPE_DIAG_MAIN_BEGIN      0x10
#define SUBTYPE_DIAG_MAIN_END        0x20
#define SUBTYPE_DIAG_OPPOSITE_BEGIN  0x40
#define SUBTYPE_DIAG_OPPOSITE_END    0x80

#define SUBTYPE_DIAG_ALL  SUBTYPE_DIAG_MAIN_BEGIN\
                         | SUBTYPE_DIAG_MAIN_END \
                         | SUBTYPE_DIAG_OPPOSITE_BEGIN\
                         | SUBTYPE_DIAG_OPPOSITE_END

#define SUBTYPE_COLUMN_TOP           1024
#define SUBTYPE_COLUMN_BOTTOM        2048
#define SUBTYPE_LINE_LEFT            4096
#define SUBTYPE_LINE_RIGHT           8192
//
// Special movement notation
//
#define SPECIAL_MOVEMENT_CASTLE      16384
#define SPECIAL_MOVEMENT_EN_PASSANT  32768
#define SPECIAL_MOVEMENT_PROMOTE     65536
#define SPECIAL_MOVEMENT_ALL         SPECIAL_MOVEMENT_CASTLE | SPECIAL_MOVEMENT_EN_PASSANT | SPECIAL_MOVEMENT_PROMOTE

#define MOVEMENT_CASTLE_SHORT 1
#define MOVEMENT_CASTLE_LONG  2
#define MOVEMENT_CASTLE_BOTH  3
//
// Compount movement notation
//
#define MAIN_DIAGONAL         SUBTYPE_DIAG_MAIN_BEGIN | SUBTYPE_DIAG_MAIN_END
#define OPPOSITE_DIAGONAL     SUBTYPE_DIAG_OPPOSITE_BEGIN | SUBTYPE_DIAG_OPPOSITE_END
//
// Full movement notation
//
#define MOVEMENT_DIAGONAL_X     MAIN_DIAGONAL | OPPOSITE_DIAGONAL
#define MOVEMENT_DIRECTION_ALL  MOVEMENT_DIRECTION_COLUMN\
                                | MOVEMENT_DIRECTION_LINE \
                                | MOVEMENT_DIRECTION_DIAGONAL\
                                | MOVEMENT_DIRECTION_L

#define MOVEMENT_COLUMN_ALL  SUBTYPE_COLUMN_TOP | SUBTYPE_COLUMN_BOTTOM
#define MOVEMENT_LINE_ALL    SUBTYPE_LINE_LEFT  | SUBTYPE_LINE_RIGHT
#define MOVEMENT_MAIN_ALL    MOVEMENT_COLUMN_ALL | MOVEMENT_LINE_ALL | SUBTYPE_DIAG_ALL

#define MOVEMENT_DIRECTION_SUBTYPE_ALL   MOVEMENT_DIRECTION_ALL | MOVEMENT_MAIN_ALL
#define MOVEMENT_TYPE_ALL                MOVEMENT_DIRECTION_ALL | MOVEMENT_MAIN_ALL | SPECIAL_MOVEMENT_ALL

//////////////////////////////////////////////////////////
//
// Piece block
//

// ROOK
#define ROOK_INITIAL_MOVEMENT     MOVEMENT_DIRECTION_COLUMN\
                                | MOVEMENT_DIRECTION_LINE  \
                                | SPECIAL_MOVEMENT_CASTLE
#define ROOK_CASTLED_MOVEMENT     (ROOK_INITIAL_MOVEMENT ^ SPECIAL_MOVEMENT_CASTLE)
#define ROOK_MOVEMENT_RANGE       LINE_OF_SIGHT

// KNIGHT
#define KNIGHT_MOVEMENT   MOVEMENT_DIRECTION_L
#define KNIGHT_MOVEMENT_RANGE     L_RANGE // 2 movements 4way expressed

// BISHOP
#define BISHOP_MOVEMENT   MOVEMENT_DIRECTION_DIAGONAL
#define BISHOP_MOVEMENT_RANGE     LINE_OF_SIGHT

// QUEEN
#define QUEEN_MOVEMENT    MOVEMENT_DIRECTION_COLUMN \
                                | MOVEMENT_DIRECTION_LINE \
                                | MOVEMENT_DIRECTION_DIAGONAL
#define QUEEN_MOVEMENT_RANGE      LINE_OF_SIGHT

// KING
#define KING_INITIAL_MOVEMENT     SPECIAL_MOVEMENT_CASTLE\
                                 | MOVEMENT_DIRECTION_COLUMN\
                                 | MOVEMENT_DIRECTION_LINE\
                                 | MOVEMENT_DIRECTION_DIAGONAL
#define KING_CASTLED_MOVEMENT     (KING_INITIAL_MOVEMENT ^ SPECIAL_MOVEMENT_CASTLE)
#define KING_MOVEMENT_RANGE       SQUARE_RANGE

// PAWN
#define PAWN_INITIAL_MOVEMENT     MOVEMENT_DIRECTION_COLUMN\
                                  | SUBTYPE_COLUMN_TOP \
                                | MOVEMENT_DIRECTION_DIAGONAL\
                                  | SUBTYPE_DIAG_MAIN_BEGIN\
                                  | SUBTYPE_DIAG_OPPOSITE_END\
                                | SPECIAL_MOVEMENT_PROMOTE\
                                | SPECIAL_MOVEMENT_EN_PASSANT
#define PAWN_PASSE_MOVEMENT      (PAWN_INITIAL_MOVEMENT ^ SPECIAL_MOVEMENT_EN_PASSANT)
#define PAWN_INITIAL_RANGE       DOUBLE_SQUARE_RANGE
#define PAWN_MOVED_RANGE         SQUARE_RANGE

#define PIECE_TYPE_ROOK     "R"
#define PIECE_TYPE_KNIGHT   "N"
#define PIECE_TYPE_BISHOP   "B"
#define PIECE_TYPE_QUEEN    "Q"
#define PIECE_TYPE_KING     "K"
#define PIECE_TYPE_PAWN     "P"
#define PIECE_TYPE_NONE      0


#define pieceColumnLookup ( \
    PIECE_TYPE_KNIGHT,\
    PIECE_TYPE_BISHOP,\
    PIECE_TYPE_QUEEN, \
    PIECE_TYPE_KING, \
    PIECE_TYPE_BISHOP,\
    PIECE_TYPE_KNIGHT, \
    PIECE_TYPE_ROOK )


#endif				// PAWN CHESS_H_INCLUDED
